### ISSUE TITLE
Registration Page error

### ISSUE THREAD

**Issue by okoliec** [AAROC/DevOps#213]
Hello @fmarco76 @brucellino,

I just completed an ldap and idp delpoyment using ansible. Everything was successful except for the registration page form after completing the form and hiting the submit button.

I got a tomcat server error page. I just pasted some portion of the page. Please you can try registering  an account on this page and see the error. I have also pasted d error i got below the page.

https://idp.uac.bj/register

See
org.hibernate.exception.GenericJDBCException: Cannot open connection
	org.hibernate.exception.SQLStateConverter.handledNonSpecificException(SQLStateConverter.java:103)
	org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:91)
	org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:29)
	org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:426)
	org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:144)
	org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:119)
	org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:57)
	org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1326)
	it.infn.ct.security.actions.AddUser.validate(AddUser.java:132)

**Comment by fmarco76** [comment]
Hi @okoliec ,

it seems there is a problem with the DB file. Could you check the file path (should be in the file hibernate.cfg.xml inside your webapp). See if the file is created or not and eventually the reasons (permission, not existing path, etc...)

**Comment by okoliec** [comment]
This is the path to the file
[root@idp WEB-INF]# less classes/hibernate.cfg.xml
<property name="hibernate.connection.driver_class">org.hsqldb.jdbcDriver</property>
    <property name="hibernate.connection.url">jdbc:hsqldb:file:/var/run/db/hsqldb/idp</property>

I think the file is also created
[root@idp WEB-INF]# ls -al /var/run/db/hsqldb/
total 24
drwxr-xr-x. 3 tomcat tomcat 4096 Apr 11 23:54 .
drwxr-xr-x. 3 tomcat tomcat 4096 Apr 10 23:22 ..
-rw-r--r--. 1 tomcat tomcat   16 Apr 12 00:19 idp.lck
-rw-r--r--. 1 tomcat tomcat    0 Apr 11 23:54 idp.log
-rw-r--r--. 1 tomcat tomcat   85 Apr 11 23:54 idp.properties
-rw-r--r--. 1 tomcat tomcat 2606 Apr 11 23:54 idp.script
drwxr-xr-x. 2 tomcat tomcat 4096 Apr 10 23:24 idp.tmp

**Comment by fmarco76** [comment]
yes, the file is there. Is tomcat running as tomcat user? Is not there is not write permission.

Could you check if the file timestamp change when you try to register? If you have not pending registration you could delete the files and make tomcat re-create them.

The problem is there but I am not sure what it is (Are you using SE linux or similar?)

**Comment by okoliec** [comment]
this is the permission i have on the tomcat folder
[root@idp webapps]# ls -al
total 11684
drwxrwxr-x.  4 root   tomcat     4096 Apr 11  2015 .
drwxrwxr-x.  3 root   root       4096 Apr 10  2015 ..
drwxr-xr-x. 10 tomcat tomcat     4096 Apr 11  2015 ROOT
drwxr-xr-x. 10 tomcat tomcat     4096 Apr 10  2015 ROOT.old
-rw-r--r--.  1 root   root   11945655 Apr 10  2015 ROOT.war

I noticed Selinux was in enforcing mode  but i have disabled it now
[root@idp webapps]# getenforce 
Disabled

But am still getting the same error

**Comment by okoliec** [comment]
Hello Marco,
Please am still stocked with this issue. Any clues on how to resolve would
be appreciated.

Thanks and hope you are good.

kind regards
Cletus

**Comment by fmarco76** [comment]
Hi Cletus,

I was out for a conference. Is the problem still there? Have you done any test?
Logs?

**Comment by okoliec** [comment]
Hello Marco,
Hope the conference was fruitful.

Yeah the problem is still there and i can. I have looked at the logs and
noticed this error after i restarted tomcat.

sorImpl.java:43) ~[na:1.7.0_79]

at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_79]

at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:289)
[bootstrap-6.0.24.jar:na]

at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:414)
[bootstrap-6.0.24.jar:na]

06:37:40.720 - ERROR
[edu.internet2.middleware.shibboleth.common.config.BaseService:188] -
Configuration was not loaded for shibboleth.AttributeResolver service,
error creating components.  The root cause of this error was:
edu.internet2.middleware.shibboleth.common.attribute.resolver.AttributeResolutionException:
Unable to retrieve LDAP connection


But i noticed i could login with the ldap admin user and password from the
web interface. The problem is that i cannot register users. Each time i
registered a user and submitted. it retrns this error

org.hibernate.exception.GenericJDBCException: Cannot open connection


Thanks

**Comment by damas** [comment]
Hi Okolie,
Are you talking about the communication between IdP and ldap? I have the same related, on my side at the IdP web page gives an error of unknown username/password when trying to login. 
And on registration it kept on loading for awhile and finally will end up with an error “username already assigned” and “Email already registered”

Team, any clue please?

Rgds,
Damas

Network Eng | CTO | TERNET
Mob: +255 754|714 464678
Skype: dmakweba
Alt.Email: dmakweba@icloud.com

**Comment by okoliec** [comment]
@damas 
Have you tried another username/password or registering another user to test with. What did your idp log say

Below is a description of my own issue
I believe the communication btw the IdP and Ldap is fine in my case as I am able to login with the initial user i created during installation from the login menu on the Idp web UI. The problem i am experiencing is that i can not register new users from the registration page. Each time a user completed the form and submitted it returns an error page
https://idp.unilag.edu.ng/register

**Comment by fmarco76** [comment]
@okoliec 

The LDAP is configured in three different place. The shibboleth attribute resolver uses its configuration and it is different from the one used by the web interface. To fix the attribute resolver error you have to check the LDAP configuration in ``attribute-resolver.xml`` inside your shibboleth idp configuration.

For the other error it seems a problem with hibernate but I am not sure if it is for the configuration or
your tomcat has some library generating a configuration conflict. It seems from your previous post that the file get generated so I am not sure why hibernate cannot access them after.

You follow the ansible installation, right? Which OS (and other configuration) are you using? I have to replicate the error in my site to investigate its origin and find a solution.

**Comment by damas** [comment]
Hi Okolie,
I fixed my problem and now I can be able to login and users can be able to register. I think I can assist to fix yours as well however mine was fixed manually and not over ansible, so we can share what is configured in some of the files so that you can try to tell ansible fix them. 
As per Marco’s email try to check those files.
Rgds,
Damas

Network Eng | CTO | TERNET
Mob: +255 754|714 464678
Skype: dmakweba
Alt.Email: dmakweba@icloud.com

**Comment by okoliec** [comment]
@fmarco76 

I have checked the file and compared with the one i did manually nut experiencing the same problem.

Yes i followed the ansible installation. See the OS i installed on
[root@idp conf]# lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.6 (Final)
Release:	6.6
Codename:	Final

@damas 
Can you point me to some the changes you made and the lines. Maybe that would help me fix the errors too.

**Comment by damas** [comment]
Hi Okolie,
My apology that I didn’t get time to come back as per your email. Do you still have problem or it is solved? if yes, can we have a Skype may be by tomorrow whereby I can try to share what I have or what I changed for my IdP to work?

Rgds,
Damas

Network Eng | CTO | TERNET
Mob: +255 754|714 464678
Skype: dmakweba
Alt.Email: dmakweba@icloud.com

**Comment by fmarco76** [comment]
Is the problem still there? Did you find the configuration error?

**Comment by okoliec** [comment]
@fmarco76 

The problem is still there. I have not been able to find the configuration error.

@damas 
Please when can you be available online so we can try yo look at the configs together. Sorry i was on transit when i saw your mail 2 days ago.

**Comment by okoliec** [comment]
@fmarco76 

I found out  while troubleshooting that tomcat was trying to read a ROOT.old instead of ROOT directory (/var/lib/tomcat6/webapps/ while restarting.

I removed the ROOT.old and the registration page now works.

Please i can't seem to find a place to approve the user. When I logged the user was not showing up as usual to approve him so he can login to the IdP.

Thanks

**Comment by fmarco76** [comment]
This problem with ROOT.old is strange but I will investigate and fix it in ansible. I'll open an Issue for this

If you are in tthe administrator group for the IdP (look in your LDAP) you should see the link to the authorisation page. If you are not please add your account.

Of course in the ldap configuration there is the name of the administrator group, take care to match the one in LDAP.

**Comment by okoliec** [comment]
The user am using is in the administrator group but  am not seeing the authorisation page. See output. I am using the user admin.

root@ldapnew:/etc/ldap# ldapsearch -x -H ldap:/// -b cn=Administrator,ou=Group,dc=idp,ou=Services,dc=local
# extended LDIF
#
# LDAPv3
# base <cn=Administrator,ou=Group,dc=idp,ou=Services,dc=local> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# Administrator, Group, idp, Services, local
dn: cn=Administrator,ou=Group,dc=idp,ou=Services,dc=local
objectClass: groupOfUniqueNames
objectClass: top
cn: Administrator
uniqueMember: cn=useradmin,dc=local
uniqueMember: cn=admin,ou=People,dc=local
description: Users in this group have administrative privileges on this server

**Comment by damas** [comment]
@Okolie,
I don’t know how to fix this but you supposed to get something like this one below;

[root@ldap ~]# ldapsearch -x -H ldap:/// -b cn=Administrator,ou=Group,dc=idp,ou=Services,dc=local
# extended LDIF
#
# LDAPv3
# base <cn=Administrator,ou=Group,dc=idp,ou=Services,dc=local> with scope subtree
# filter: (objectclass=*)
# requesting: ALL
#

# Administrator, Group, idp, Services, local
dn: cn=Administrator,ou=Group,dc=idp,ou=Services,dc=local
objectClass: groupOfUniqueNames
objectClass: top
cn: Administrator
description: Users in this group have administrative privileges on this server
uniqueMember: cn=damas,ou=People,dc=local

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1

May be a question is, how did you create user who you need to be Administrator? I remember, since we deployed manually (before using ansible) the first user we created was administrator and for this case you supposed to be you.

Rgds,
Damas

Network Eng | CTO | TERNET
Mob: +255 754|714 464678
Skype: dmakweba
Alt.Email: dmakweba@icloud.com

**Comment by okoliec** [comment]
I created using ansible. The first user i added is the user idpadmin. Am surprised that i cant find the authorisation page as posted. Just some clearification.
what is the difference between these two users
# Administrator, Group, idp, Services, local
dn: cn=Administrator,ou=Group,dc=idp,ou=Services,dc=local
objectClass: groupOfUniqueNames
objectClass: top
cn: Administrator
uniqueMember: cn=useradmin,dc=local
uniqueMember: cn=idpadmin,ou=People,dc=local
description: Users in this group have administrative privileges on this server

# search result
search: 2
result: 0 Success

I can login with idpadmin but cannot login with useradmin
